### ISSUE TITLE
代码跑不起来

### ISSUE THREAD

**Issue by 13191868165** [cloydlau/minimce#10]
代码跑不起来，如下图，没有任何报错信息
![@ORSSQ1}`CY9ER%LDKC{DOM](https://user-images.githubusercontent.com/7892146/183879096-8fd51060-15c9-407c-afae-887fb0667374.png)

**Comment by cloydlau** [comment]
Deno 装了吗？运行脚本依赖 Deno，不过如果没装的话应该会报错的。

我无法复现你的问题，请尝试拉取最新代码，删除 `pnpm-lock.yaml` 文件，删除 `node_modeuls`，重新安装依赖。

**Comment by 13191868165** [comment]
Deno安装了，删掉 pnpm-lock.yaml 后产生了新的错误
![YLPCQV N7 C`{H `UFV6 D](https://user-images.githubusercontent.com/7892146/184050562-ba1d75e6-b9da-4365-9f6b-8096c9bd4792.png)
