### ISSUE TITLE
demo如何才能运行起来？

### ISSUE THREAD

**Issue by IceApriler** [cloydlau/minimce#7]
目前尝试多条命令都报错了，大佬有空帮忙看下~
```bash
npm run dev2
```
![image](https://user-images.githubusercontent.com/29689307/182104426-ddf965a4-a0d3-440b-add1-1decee80ef08.png)

```bash
npm run dev
```
![image](https://user-images.githubusercontent.com/29689307/182105151-5d484429-323b-4689-b78b-d30339f80c07.png)

**Comment by cloydlau** [comment]
要自己启动的话，请确保安装了 pnpm，以及 node 版本为 14 以上。先关闭了，如果确实有问题再打开。

**Comment by IceApriler** [comment]
大佬，我已经用node 16 运行起来了，控制台报下图这样的错。我还有什么需要注意的吗
![image](https://user-images.githubusercontent.com/29689307/182109197-5c4e819a-e782-48d5-b658-3fc565840eb5.png)

**Comment by cloydlau** [comment]
这个问题是 switch-vue 脚本暂时没做 vue2.7 的兼容导致的，dev 命令无问题，先用着 dev，我待会儿把 switch-vue 脚本弄一下。

**Comment by IceApriler** [comment]
好的，感谢！
