### ISSUE TITLE
powerpaste插件无效 是新版本被去除了么

### ISSUE THREAD

**Issue by yourenyouyu** [cloydlau/minimce#9]

**Comment by cloydlau** [comment]
powerpaste 从来都是付费插件哈，minimce 不会以非法手段内置付费插件。minimce 的定位是 tinymce 的离线版超集，tinymce 支持的 minimce 都能支持。用户想搞什么付费插件是他们自己的事情了。
说起来，插入 word 文档这个功能，实际上就是对 powerpaste 能够解析粘贴的 word 文档内容这个功能的一个替代。不过最后发现效果还挺不错，对 wps 的支持度等都比 powerpaste 强。
所以如果 minimce 可以自己实现 powerpaste 用于解析网页内容那块的逻辑，那当然也是很不错的。pr welcome

**Comment by yourenyouyu** [comment]
插入 word 文档那个包不支持word样式好像，目前除了这个有什么替换powerpaste的更好的方案嘛
